AWSTemplateFormatVersion: '2010-09-09'
Description: Builld S3 and inline lambdas
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cloudformation-build-incidentsdashboard-jaworra

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Inline Yaml lambda build
      FunctionName: test_jaworra_cloudformation_build_inline
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::708280501988:role/lambda_generic
      Runtime: python2.7 
      Code:
        ZipFile: |
          #Sample of Inline lambda function
          #Disadv of this approach - external libraries cannot be used, certain characters must be escaped and in JSON templates
          #This approach is best suited for function code that is simple and does not change frequently
          #todo: test limit of functionality
          import json
          def handler(event, context):
            print 'inline deployment'
            print("Event: %s" % json.dumps(event))
            return 

  lambdaFunction2:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda via s3 Bucket
      FunctionName: test_jaworra_cloudformation_build_S3
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::708280501988:role/lambda_generic
      Runtime: python2.7 
      Code:
        S3Bucket: deployment-artefacts-jaworra 
        S3Key: test_jaworra_cloudformation_build_s3.zip #Update S3 Key with every upload
=
