AWSTemplateFormatVersion: '2010-09-09'
Description: Builld S3 and inline lambda
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cloudformation-build-incidentsdashboard-jaworra

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Python Function Handler
      FunctionName: test_jaworra_cloudformation_build
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::708280501988:role/lambda_generic
      Runtime: python2.7 
      Code:
        ZipFile: |
          import json
          def handler(event, context):
          	response = {
          		'statusCode': 200,
          		'body': json.dumps('Hello Python')
          	}
          	return response
