AWSTemplateFormatVersion: '2010-09-09'
Description: Builld S3 and inline lambdas
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cloudformation-build-incidentsdashboard-jaworra

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Python Function Handler
      FunctionName: test_jaworra_cloudformation_build
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::708280501988:role/lambda_generic
      Runtime: python2.7 
      Code:
        ZipFile: |
          #Feature extraction from available API
          #todo: 1) refactor holiday and next 24 hour result
          #      2) set cloud watch  

          # Based on location of incident ('In progres') return proximity HERE flow network
          # Save S3 location
          bucketname_routes="public-test-road"
          filepath_incidents_read_prefix_key="stat/"
          filepath_incidents_statistic_write = "public-test-road/stat/"

          # Athena parametres
          DATABASE = 'incidents'
          TABLE = 'daily_summaries_dashboard'
          S3_OUTPUT = 's3://public-test-road/stat/qry'
          S3_BUCKET = 'qry'
          RETRY_COUNT = 5 # number of retries

          #------------------ queries run on below athena table-----------------------
          #create table if required below athena db *refrence incase tabld is dropped
          '''
          CREATE EXTERNAL TABLE IF NOT EXISTS historic_incidents_db.daily_summaries_partition(
          `date` string,
          `weekday` string,
          'incidentcount` int,
          `crashcount` int 
          ) PARTITIONED BY (
          `yymmdd_utcplus10` string 
          )
          ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
          WITH SERDEPROPERTIES (
            'serialization.format' = ',',
            'field.delim' = ','
          ) LOCATION 's3://public-test-road/stat/bytime/'
          TBLPROPERTIES ('has_encrypted_data'='false')
          '''

          import boto3
          import json
          import datetime
          from datetime import date, timedelta
          from botocore.vendored import requests
          import urllib2
          import json

          from athena_lambda import *