AWSTemplateFormatVersion: '2010-09-09'
Description: Builld S3 and inline lambdas
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: cloudformation-build-incidentsdashboard-jaworra

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Python Function Handler
      FunctionName: test_jaworra_cloudformation_build
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::708280501988:role/lambda_generic
      Runtime: python2.7 
      Code:
        ZipFile: |
          #Sample of Inline lambda function
          #todo: 1) test limit of functionality
          import json
          def handler(event, context):
            print 'testing'
            print("Event: %s" % json.dumps(event))